### ISSUE TITLE
Helper Script Not Working... Need help with "YOUTUBE_TOKEN" env var

### ISSUE THREAD

**Issue by bolbken** [cedricdelpoux/gatsby-source-google-photos#1]
I'd like to use your plugin, but I can't figure out how to get the API tokens for the (potentially mis-named) "YOUTUBE_TOKEN".  I started with your helper script, but it is automatically logging me into a default account in chrome and I can't use that account.  So I need to be able to do it manually.

Since I've given up on the helper script, I've manually generated a Oath client ID and Secret and an API Token, but I'm struggling to understand how to generate the following:
* refresh_token
* scope
* token_type
* expiry_date to 

If you can help me through the process, I'm happy to add an instructional on how to manually create the creds for this repo.

Thanks

**Comment by cedricdelpoux** [comment]
Hi @bolbken sorry for the delay! Did you succeed?
