### ISSUE TITLE
Does this plugin creates Teporal based url or Sort of permament Url for google photos

### ISSUE THREAD

**Issue by kamit-transient** [cedricdelpoux/gatsby-source-google-photos#11]
Hi @cedricdelpoux and Team,

First of all many many congratulations for this plugin. 

I have a quick question, though.

@tinavanschelt has mentioned this on her [Archived Repo](https://github.com/tinavanschelt/gatsby-source-google-photos) "**Google Photos refreshes the baseUrl after 60 minutes, in other words, your images will only be visible for an hour**".

Does this plugin solve the above limitation?

Once again, thanks a ton, and congratulations to you and the team.

**Comment by cedricdelpoux** [comment]
Yes of course ! The plugin downloads all images so there is no limitations anymore
