### ISSUE TITLE
Google api is returning a next page token incorrectly

### ISSUE THREAD

**Issue by brendenmoore** [cedricdelpoux/gatsby-source-google-photos#30]
I discovered an issue with an album of mine with exactly 60 photos. For some reason after the last page of 10 photos, it returned an additional nextPageToken, which causes the following request to return an empty object and the process crashed on line 98 of sourceNodes.js.

I don't know why the google api returned an incorrect nextPageToken, but this could be circumvented easily be checking for an empty result before executing line 97. 

Adding one more photo to my album resolved this for now, and I have not done any testing to try and reproduce the issue again, but it may be worthwhile to just add the check in there so this doesn't happen in the future.

**Comment by cedricdelpoux** [comment]
Thank for reporting this. Could you make a PR to resolve this? Thanks

**Comment by brendenmoore** [comment]
https://github.com/cedricdelpoux/gatsby-source-google-photos/pull/31

**Comment by cedricdelpoux** [comment]
Thanks! Published in `3.0.1` version
