### ISSUE TITLE
Builds stuck at 'source and transform nodes'

### ISSUE THREAD

**Issue by xylophonehero** [cedricdelpoux/gatsby-source-google-photos#4]
I have played around with the code and seems to work when I change PAGE_SIZE_PHOTOS in constants.js to 10 instead of 20.

Is it possible to add this value to the plugin options?

**Comment by cedricdelpoux** [comment]
Thank you for helping. I commenting your PR and suggesting to replace the current constant because it's not consistent actually for big albums.

**Comment by xylophonehero** [comment]
No problem. That's a good idea.
