### ISSUE TITLE
Update to Gatsby 3

### ISSUE THREAD

**Issue by skoch** [cedricdelpoux/gatsby-source-google-photos#7]
Any plans to update the `gatsby` `peerDependency` to `^3.0.0`?

**Comment by cedricdelpoux** [comment]
Hi @skoch, thank you for your suggestion. I updated the peerDependency to be compatible with Gatsby v3.

You should try the latest `2.4.3` version.
Thank you

**Comment by skoch** [comment]
Merci, @cedricdelpoux
